services:
  - type: web
    name: number-guess-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001

  - type: web
    name: number-guess-client
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    envVars:
      - key: REACT_APP_SERVER_URL
        fromService:
          type: web
          name: number-guess-server
          envVarKey: RENDER_EXTERNAL_URL 